sonar.projectKey=Secure-Code-Review
sonar.projectName=Secure-Code-Review
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.token=sqp_b2063e7d0747ad3a8418cfe685ed19bcc65107d0
sonar.dependencyCheck.reportPath=C:/dependency-check-report/dependency-check-report.xml
# Exclude tests & build output
sonar.exclusions=**/test/**,**/tests/**,**/target/**,**/dist/**,**/node_modules/**
# Skip coverage if not needed
sonar.coverage.exclusions=**
sonar.scm.disabled=true
sonar.cpd.exclusions=**/*.min.js